version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - mongoURI=mongodb://admin:534tg534dfget5663@212.23.211.54:27017/myappdb?authSource=admin
    restart: unless-stopped
